config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    get "static_pages/home"
    get "static_pages/help"
    get "static_pages/contact"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    root "static_pages#home"
    delete "/logout", to: "sessions#destroy"
    resources :users
    resources :account_activations, only: :edit
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token

  before_create :create_activation_digest
  before_save{:email_downcase}

  validates :name, presence: true,
    length: {maximum: Settings.length.name}

  validates :email, presence: true,
    length: {maximum: Settings.length.email},
    format: {with: Settings.regex.email_regex},
    uniqueness: true

  validates :password, presence: true,
    length: {minimum: Settings.length.password},
    allow_nil: true

  has_secure_password

  validate :valid_birthday, if: ->{birthday.present?}

  class << self
    # Returns the hash digest of the given string.
    def digest string
      cost = if ActiveModel::SecurePassword.min_cost
               BCrypt::Engine::MIN_COST
             else
               BCrypt::Engine.cost
             end
      BCrypt::Password.create string, cost: cost
    end

    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  def remember
    self.remember_token = User.new_token
    update_attribute :remember_digest, User.digest(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute :remember_digest, nil
  end

  def authenticated? attribute, token
    digest = send "#{attribute}_digest"
    return false unless digest

    BCrypt::Password.new(digest).is_password? token
  end

  def activate
    update_columns activated: true, activated_at: Time.zone.now
  end

  def send_activation_email
    UserMailer.account_activation(self).deliver_now
  end

  private

  def valid_birthday
    return if Date.parse(birthday) > Settings.length.date.years.ago

    errors.add(:birthday, I18n.t("error.valid"))
  end

  def email_downcase
    email.downcase!
  end

  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end
end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController
  def edit
    user = User.find_by email: params[:email]
    if user && !user.activated && user.authenticated?(:activation, params[:id])
      user.activate
      log_in user
      flash[:success] = t "active_account.active_success"
      redirect_to user
    else
      flash[:danger] = t "active_account.invalid_link"
      redirect_to root_url
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  include SessionsHelper
  before_action :set_locale

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    {locale: I18n.locale}
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by email: params[:session][:email].downcase
    if user&.authenticate params[:session][:password]
      active_user user
    else
      flash.now[:danger] = t("login.fails")
      render :new
    end
  end

  def destroy
    log_out
    redirect_to login_url
  end

  private

  def active_user user
    if user.activated
      log_in user
      params[:session][:remember_me] == "1" ? remember(user) : forget(user)
      redirect_back_or user
    else
      flash[:warning] = t "active_account.not_actived"
      redirect_to root_url
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home; end

  def help; end

  def contact; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, except: %i(new show create)
  before_action :load_user, except: %i(index new create)
  before_action :correct_user, only: %i(edit update)

  def new
    @user = User.new
  end

  def show; end

  def create
    @user = User.new user_params
    if @user.save
      @user.send_activation_email
      flash[:info] = t "active_account.send_confirm"
      redirect_to root_url
    else
      render :new
    end
  end

  def index
    @pagy, @users = pagy(User.all, items: Settings.length.items)
  end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:success] = t "users.update.success"
      redirect_to @user
    else
      render "edit"
    end
  end

  def destroy
    if user&.destroy
      flash[:success] = t "users.destroy.success"
    else
      flash[:danger] = t "users.destroy.danger"
    end
    redirect_to users_url
  end

  private

  def load_user
    @user = User.find_by id: params[:id]
    return if @user

    flash[:danger] = t "users.not_found"
    redirect_to root_url
  end

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation,
      :birthday,
      :gender
    )
  end

  def logged_in_user
    return if logged_in?

    store_location
    flash[:danger] = t "users.login.danger"
    redirect_to login_url
  end

  def correct_user
    @user = User.find_by(id: params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
  def full_title page_title = ""
    base_title = t "base_title"
    page_title.empty? ? base_title : "#{page_title} | #{base_title}"
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def logged_in?
    current_user.present?
  end

  def remember user
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by id: user_id
    elsif user_id = cookies.signed[:user_id]
      user = User.find_by id: user_id
      if user&.authenticated?(:remember, cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  def forget user
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  def current_user? user
    user == current_user
  end

  def redirect_back_or default
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, options = {size: Settings.avatar.size}
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t("nav.logo"), static_pages_home_url, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t("nav.home"), static_pages_home_url %></li>
        <li><%= link_to t("nav.help"), static_pages_help_path %></li>
        <% if logged_in? %>
          <li><%= link_to t("nav.users"), users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" >
              <%= t("nav.account") %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to t("nav.profile"), current_user %></li>
              <li><%= link_to t("nav.settings"), edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li> <%= link_to t("nav.logout"), logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to t("nav.login"), login_path %></li>
        <% end %>
        <li><%= link_to t(".english"), locale: :en %></li>
        <li><%= link_to t(".vietnamese"), locale: :vi %> </li>   
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>    
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t ".the_form_contains" %>
      <%= pluralize @user.errors.count, "error" %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/contact.html.erb
<% provide :title,  t("contact.title")  %>
<%= t "contact.hello" %>

app/views/static_pages/help.html.erb
<% provide :title, t("help.title") %>
<h1><%= t "help.title" %></h1>
<p><%= t "help.content_html" %></p>

app/views/static_pages/home.html.erb
<% provide :title, t("home.title") %>
<div class="center jumbotron">
  <h1><%= t "home.content_h1" %></h1>
  <h2><%= t "home.content_h2_html" %></h2>
  <%= link_to t("home.signup"), signup_url , class: "btn btn-lg btn-primary" %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render "shared/error_messages" %>
  <%= f.label :name, t("signup.name") %>
  <%= f.text_field :name, class: "form-control" %>
  <%= f.label :email, t("signup.email") %>
  <%= f.email_field :email, class: "form-control" %>
  <%= f.label :password, t("signup.password") %>
  <%= f.password_field :password, class: "form-control" %>
  <%= f.label :password_confirmation, t("signup.confirm_password") %>
  <%= f.password_field :password_confirmation, class: "form-control" %>
  <%= f.label :birthday, t("signup.birthday") %>
  <%= f.text_field :birthday, class: "form-control", type: "date" %>
  <%= f.label :gender, t("signup.gender") %>
  <%= f.select :gender, options_for_select(Settings.form.option_gender, selected:  :gender) %>
  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: Settings.avatar.size %>
  <%= link_to user.name, user %>
  <% if current_user.admin? && !current_user?(user) %>
    <%= link_to t("users.index.btn_delete"), user, method: :delete, data: {confirm: t("users.index.confirm_delete")} %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide :title, t("users.edit.title") %>
<% provide :button_text, t("users.edit.btn_submit") %>
<h1><%= t "users.edit.subject" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <%= link_to t("users.edit.avatar_change"), Settings.url.gravatar, target: "_blank" %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide :title, t("users.index.title") %>
<h1><%= t "users.index.subject" %></h1>
<%== pagy_nav(@pagy) %>
<ul class="users">
  <%= render @users %>
</ul>

app/views/users/new.html.erb
<% provide :title, t("signup.title") %>
<% provide :button_text, t("signup.create_my_account") %>
<h1><%= t "signup.title" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>    
  </div>
</div>

app/views/users/show.html.erb
<% provide :title, @user.name %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>